// <auto-generated />
namespace DevelopingWithWindowsAzure.Shared.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddVideoStatusColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVideoStatusColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201210091541295_AddVideoStatusColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
